### ISSUE TITLE
Version 2.1.0 throws unhandled error during formatting

### ISSUE THREAD

**Issue by Siegrift** [prettier-solidity/prettier-plugin-solidity#1218]
```
[error] contracts/<CONTRACT_NAME>: Error: We encountered the following syntax error:
[error]
[error] 	Expected EqualGreaterThan.
[error]
[error] Based on the pragma statements, we inferred your code to be using Solidity version 0.8.17. If you would like to change that, update the pragmas in your source file, or specify a version in your `.prettierrc` file.
```

My contract starts with the following:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;
```

which seems to be parsed well in other files, so I dunno what actually causes the error. However, everything works fine with with version `2.0.0` (I noticed this issue during dependency upgrade). Unfortunately, I can't share the contract implementation details.

**Comment by Siegrift** [comment]
Some of the contracts we use are external and we use multiple version of the compiler (some contracts mandate a fixed version). Here's how my `hardhat.config.ts` looks like:
```
solidity: {
    compilers: [
      {
        version: '0.8.24',
        settings: {
          optimizer: {
            enabled: true,
            runs: 100,
          },
        },
      },
      {
        version: '0.8.20',
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      },
      {
        version: '0.8.17',
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      },
      {
        version: '0.8.12',
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      },
    ],
```

I could use the compiler settings as outlined [here](https://github.com/prettier-solidity/prettier-plugin-solidity?tab=readme-ov-file#compiler), but it feels clunky to me to maintain this configuration. I'd much rather specify a set of compilers that are to be used for linting (the same way as Hardhat does it).

I've found a somewhat smaller reproducible example. I basically removed all other contracts, and left only [this contract](https://github.com/Uniswap/permit2/blob/main/src/interfaces/IAllowanceTransfer.sol) (and its dependencies). The output I get when I run the prettier format is:
```
contracts/external/uniswap/permit2/interfaces/IAllowanceTransfer.sol
[error] contracts/external/uniswap/permit2/interfaces/IAllowanceTransfer.sol: Error: We encountered the following syntax error:
[error]
[error] 	Expected Equal or Semicolon.
[error]
...
```

I now see that the prettier complains about the use of [errors](https://github.com/Uniswap/permit2/blob/cc56ad0f3439c502c246fc5cfcc3db92bb8b7219/src/interfaces/IAllowanceTransfer.sol#L12), which are only supported since v0.8.4... I think this will be a rather widespread issue, because people often change their version in HH config and forget to update the pragmas. For me, it's much more convenient to stay on version 2.0.0 rather then sort this out in all of the affected contracts just to have the formatting working.

**Comment by fvictorio** [comment]
@Siegrift I just published `prettier-plugin-solidity@2.2.0-rc.0` (from [this PR](https://github.com/prettier-solidity/prettier-plugin-solidity/pull/1225)).

Could you install `prettier-plugin-solidity@rc` and check if it fixes your issue?

**Comment by Siegrift** [comment]
Mhh, tried that just now and it still appears to format the files using 0.8.0 version 🤔

**Comment by fvictorio** [comment]
Sorry, my bad, I did a half-assed fix. Can you try again with `2.2.0-rc.1`?

**Comment by Siegrift** [comment]
Indeed that causes no issues for us anymore. I tried it on our full repo with a bunch of external contracts and I got some lint breakages, but no errors.

**Comment by OmarTawfik** [comment]
> so I dunno what actually causes the error.

@fvictorio @Janther I suggest including the line/column in the error message, to make it easier to pinpoint the offending syntax?

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/254cff2d8747b0f7045c9d6de7ac95cc0422b8cd/src/slang-utils/create-parser.ts#L29

**Comment by Siegrift** [comment]
@fvictorio Any estimate when the 2.2.0 version will be released?

**Comment by Janther** [comment]
hi @Siegrift,

I'm waiting for the next `slang` version that should be coming soon and hopefully some of the performance PR's to be reviewed and included.

**Comment by wighawag** [comment]
I am hitting the same issue and that's actually cool to have these error somehow (though it will great if it was optional), also for the errors if we could get the exact line, col number that would be great

**Comment by OmarTawfik** [comment]
> I am hitting the same issue and that's actually cool to have these error somehow (though it will great if it was optional), also for the errors if we could get the exact line, col number that would be great

@Janther might be helpful to include the error location (line/col) in the error message. See https://github.com/prettier-solidity/prettier-plugin-solidity/issues/1218#issuecomment-3140624991
