### ISSUE TITLE
Override modifier getting deleted ?

### ISSUE THREAD

**Issue by ianmihura** [prettier-solidity/prettier-plugin-solidity#277]
So, this might not be the correct place to post this. I'm coming from VScode, using this [Solidity extension](https://github.com/juanfranblanco/vscode-solidity), which seems to be using your module to format the code, [in :14](https://github.com/juanfranblanco/vscode-solidity/blob/master/src/formatter/prettierFormatter.ts)

Might be the problem is coming from another place, tho I doubt it, as the VScode extension seems to manage the `override modifier missing` error correctly, and the problem arises only as the formatter is applied to the file. 

Anyway, a similar issue already exists in the appropriate repo, [issue 174](https://github.com/juanfranblanco/vscode-solidity/issues/174), I'm only passing thru to check on you guys as well.

Cheers

**Comment by abcoathup** [comment]
Using https://github.com/juanfranblanco/vscode-solidity formatting a contract with the override keyword results in the override keyword being removed
## Unformatted
```solidity
pragma solidity ^0.6.0;


contract A {
    function doStuff() public virtual {}
}


contract B is A {
    function doStuff() public override {}
}
```
## Formatted
```solidity
pragma solidity ^0.6.0;


contract A {
    function doStuff() public virtual {}
}


contract B is A {
    function doStuff() public {}
}
```

**Comment by Janther** [comment]
This was solved on version [v1.0.0-alpha.49](https://github.com/prettier-solidity/prettier-plugin-solidity/releases/tag/v1.0.0-alpha.49)
Perhaps @juanfranblanco can post a newer release pointing to the latest release?

**Comment by juanfranblanco** [comment]
@Janther @ianmihura yes it is is already there.. i was testing the caching feature before release.

**Comment by ianmihura** [comment]
Great, thank you, amazing work 🙌

**Comment by Janther** [comment]
Closing since this `vs-code` has been updated

**Comment by smoove** [comment]
This problem still exists for contract state variables:

Before formatting: `mapping(address => bool) public override varName;`
After formatting: `mapping(address => bool) public varName;`

**Comment by mattiaerre** [comment]
the same problem here do you think @Janther ?

**Comment by Janther** [comment]
Nope, this one is on us, first I’ll check if the parser identifies
`virtual` and `override` in these cases

**Comment by fvictorio** [comment]
Was this fixed by #281?

**Comment by fvictorio** [comment]
Oh, modifiers still pending, sorry.

**Comment by PaulRBerg** [comment]
Using vscode-solidity@0.0.72 and prettier-plugin-solidity@1.0.0-alpha.53 and the `override` keyword is still getting deleted on a non-abstract contract.

**Comment by mattiaerre** [comment]
I'm gonna close this issue then 😊
